### ISSUE TITLE
 Cannot inherit from final class in CsvMapper mapper = new CsvMapper();

### ISSUE THREAD

**Issue by Uditmittal** [FasterXML/jackson-dataformat-csv#120]
Exception in thread "main" java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.fasterxml.jackson.dataformat.csv.CsvMapper.<init>(CsvMapper.java:39)
	at CsvCreator.main(CsvCreator.java:64)

My maven dependency is 
                      <dependency>
			  <groupId>com.fasterxml.jackson.dataformat</groupId>
			  <artifactId>jackson-dataformat-csv</artifactId>
			  <version>2.7.0</version>
			</dependency>

When i changed the version 
<dependency>
			  <groupId>com.fasterxml.jackson.dataformat</groupId>
			  <artifactId>jackson-dataformat-csv</artifactId>
			  <version>2.5.0</version>
			</dependency>

it works Fine ..

**Comment by cowtowncoder** [comment]
I don't see anything that would let me know what might be wrong.

But typically problems like this are due to incompatible versions: make sure that all your Jackson components have same minor version: with dataformat-csv 2.7 you MUST use `jackson-core` and `jackson-databind` of 2.7 as well.
